// ignore_for_file: unused_import, non_constant_identifier_names

import 'package:flutter/material.dart';

//name 1
List<String> names = [
  "Alexander",
  "Sophia",
  "Benjamin",
  "Olivia",
  "William",
  "Emma",
  "James",
  "Ava",
  "Henry",
  "Isabella",
  "Michael",
  "Mia",
  "Daniel",
  "Charlotte",
  "Matthew",
  "Amelia",
  "Joseph",
  "Harper",
  "David",
  "Evelyn",
  "Samuel",
  "Abigail",
  "Christopher",
  "Ella",
  "Andrew",
  "Grace",
  "Joshua",
  "Lily",
  "John",
  "Scarlett",
  "Ryan",
  "Zoey",
  "Logan",
  "Madison",
  "Lucas",
  "Penelope",
  "Nathan",
  "Aria",
  "Elijah",
  "Layla",
  "Gabriel",
  "Chloe",
  "Caleb",
  "Victoria",
  "Anthony",
  "Nora",
  "Julian",
  "Hazel",
  "Owen",
  "Aurora"
];

//name 2
List<String> subjects = [
  'Mathematics',
  'English',
  'History',
  'Biology',
  'Chemistry',
  'Physics',
  'Geography',
  'Computer Science',
  'Art',
  'Music',
  'Physical Education',
  'Health',
  'Economics',
  'Business Studies',
  'Accounting',
  'Literature',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Political Science',
  'Environmental Science',
  'Drama',
  'Dance',
  'Engineering',
  'Astronomy',
  'Statistics',
  'Graphic Design',
  'Photography',
  'Journalism',
  'Creative Writing',
  'French',
  'Spanish',
  'German',
  'Chinese',
  'Japanese',
  'Latin',
  'Religious Studies',
  'Anthropology',
  'Archaeology',
  'Marine Biology',
  'Genetics',
  'Microbiology',
  'Zoology',
  'Botany',
  'Astrophysics',
  'Calculus',
  'Algebra',
  'Geometry',
  'Trigonometry',
  'Literary Analysis'
];

//value 1
List<int> list_numerbs1 = List.generate(51, (index) => index);

//value 2
List<int> list_numerbs2 = List.generate(51, (index) => index + 50);